dist: trusty
sudo: required
language: c++
cache: ccache

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - libstdc++6-5-dev
      - libblas3
      - liblapack3
      - python-setuptools
      - libgif-dev
      - vim-common
      - libx11-dev

env:
  global:
    - CI=false
    - OMP_NUM_THREADS=4
    - CC=gcc-5
    - CXX=g++-5

before_install:
  - sudo easy_install pip
  - sudo pip install virtualenv

script:
  - bash scripts/make_wheel.sh --build_number=$CI_PIPELINE_ID --num_procs=2 --debug