sudo: false
language: c++
cache: ccache

addons:
  apt:
    update: true
    packages:
    - libblas3
    - liblapack3
    - libstdc++6
    - python-setuptools
    - libgif-dev
    - vim-common
    - libx11-dev
    - virtualenv

script:
  - bash scripts/make_wheel.sh --build_number=$CI_PIPELINE_ID --num_procs=2 --debug